export { default as Main } from "./Main";
export { default as Navbar } from "./Navbar";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Home } from "./Home";
export { default as Routine } from "./Routine";
export { default as Activities } from "./Activities";
export { default as MyRoutines } from "./MyRoutines";
export { default as CreateNewRoutine } from "./CreateNewRoutine"
export { default as CreateNewActivity } from "./CreateNewActivity"
export { default as EditRoutine } from "./EditRoutine"
export { default as SingleRoutine } from "./SingleRoutine"